name: Deploy

on:
  push:
    branches:
      - develop*
      - release*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Step 2 - GitHub Action if statement (true)
        env:
          WHO_TO_TRUST: ${{ secrets.BASIC_USER }}
      if:  env.WHO_TO_TRUST == 'TrustNo1'
      run: echo "I know what the secret token is!"
            
    - name: 'Create Deploy Package'
      run: zip -r deploy.zip . -x '*.git*' 'README.md' 'test/\*'

    - name: 'Get current date'
      id: date
      run: echo .env
