name: Deploy

on:
  push:
    branches:
      - develop*
      - release*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Setting basic authen
      run: echo ${{ secrets.BASIC_USER }}
            
    - name: 'Create Deploy Package'
      run: zip -r deploy.zip . -x '*.git*' 'README.md' 'test/\*'

    - name: 'Get current date'
      id: date
      run: echo .env
